[package]
name = "ambot"
description = "Bot used in the AlliedModders discord server"
version = "0.1.1"
authors = ["Michael Flaherty (Headline#9999)"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full", "blocking"] }
reqwest = { version = "0.10" }
dotenv = "0.15.0"
log = "0.4"
pretty_env_logger = "0.3"
serde = { version = "1.0.*", features = ["derive"] }
quick-xml = { version = "0.20.0", features = ["serialize"] }

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]
[dependencies.gdcrunner]
path = "gdc-runner"

[dependencies.serenity]
version = "0.9"
default-features = false
features = ["collector", "gateway", "builder", "standard_framework", "http", "model", "client", "framework", "utils", "rustls_backend"]